eShopSolution.AdminApp/Controllers/ProductController.cs
using System.Linq;
using System.Threading.Tasks;
using eShopSolution.AdminApp.Models;
using eShopSolution.ApiIntegration;
using eShopSolution.Utilities.Constants;
using eShopSolution.ViewModels.Catalog.Products;
using eShopSolution.ViewModels.Common;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;

namespace eShopSolution.AdminApp.Controllers
{
    public class ProductController : BaseController
    {
        private readonly IProductApiClient _productApiClient;
        private readonly IConfiguration _configuration;

        private readonly ICategoryApiClient _categoryApiClient;

        public ProductController(IProductApiClient productApiClient,
            IConfiguration configuration,
            ICategoryApiClient categoryApiClient)
        {
            _configuration = configuration;
            _productApiClient = productApiClient;
            _categoryApiClient = categoryApiClient;
        }

        public async Task<IActionResult> Index(string keyword, int? categoryId, int pageIndex = 1, int pageSize = 4)
        {
            var request = new GetManageProductPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize,
                CategoryId = categoryId
            };

            var data = await _productApiClient.GetPagings(request);
            ViewBag.Keyword = keyword;

            var categories = await _categoryApiClient.GetAll();
            ViewBag.Categories = categories.Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString(),
                Selected = categoryId.HasValue && categoryId.Value == x.Id
            });

            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            return View(data);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            // Lấy ra danh sách các category
            var categories = await _categoryApiClient.GetAll();
            var productVM = new ProductCreateRequest()
            {
                Categories = categories
            };
            return View(productVM);
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Create([FromForm] ProductCreateRequest request)
        {
            if (!ModelState.IsValid)
            {
                request.CategoryId = 0;
                request.Categories = await _categoryApiClient.GetAll();
                return View(request);
            }

            var result = await _productApiClient.CreateProduct(request);
            if (result)
            {
                TempData["CreateProductSuccessful"] = "Thêm mới sản phẩm thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Thêm sản phẩm thất bại");
            request.CategoryId = 0;
            request.Categories = await _categoryApiClient.GetAll();
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var categories = await _categoryApiClient.GetAll();
            var product = await _productApiClient.GetById(id);
            var editVm = new ProductUpdateRequest()
            {
                Id = product.Id,
                Name = product.Name,
                CategoryId = product.CategoryId,
                Categories = categories,
                Price = product.Price,
                Stock = product.Stock,
                Description = product.Description,
                Details = product.Details,
            };

            return View(editVm);
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Edit([FromForm] ProductUpdateRequest request)
        {
            if (!ModelState.IsValid)
            {
                request.CategoryId = 0;
                request.Categories = await _categoryApiClient.GetAll();
                return View(request);
            }

            var result = await _productApiClient.UpdateProduct(request);
            if (result)
            {
                TempData["UpdateProductSuccessful"] = "Cập nhật sản phẩm thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Cập nhật sản phẩm thất bại");
            request.CategoryId = 0;
            request.Categories = await _categoryApiClient.GetAll();
            return View(request);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(new ProductDeleteRequest()
            {
                Id = id
            });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(ProductDeleteRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _productApiClient.DeleteProduct(request.Id);
            if (result)
            {
                TempData["DeleteProductSuccessful"] = "Xóa sản phẩm thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Xóa không thành công");
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var product = await _productApiClient.GetById(id);

            var category = await _categoryApiClient.GetById(product.CategoryId);

            var detailVm = new ProductViewModel()
            {
                Price = product.Price,
                Stock = product.Stock,
                Name = product.Name,
                Category = category,
                Description = product.Description,
                Details = product.Details,
                ThumbnailImage = product.ThumbnailImage,
                ProductImage = product.ProductImage
            };

            return View(detailVm);
        }
    }
}

eShopSolution.AdminApp/Views/Product/CategoryAssign.cshtml
@model eShopSolution.ViewModels.Catalog.Products.CategoryAssignRequest

@{
    ViewData["Title"] = "Gán danh mục";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <h1 class="mt-4">Gán quyền</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a style="color: #0779e4;" href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Gán danh mục</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="Product">Về danh sách</a>
        </div>

        <div class="card-body">
            <form asp-action="CategoryAssign">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                @*@for (var i = 0; i < Model.Categories.Count; i++)
                {
                    <div class="form-group">
                        <label>
                            @Model.Categories[i].Name
                            <input type="checkbox" asp-for="Categories[i].Selected" />
                            <input type="hidden" asp-for="Categories[i].Id" />
                            <input type="hidden" asp-for="Categories[i].Name" />
                        </label>
                    </div>
                }*@
                <div class="form-group">
                    <input type="submit" value="Lưu lại" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

eShopSolution.AdminApp/Views/Product/Create.cshtml
@model eShopSolution.ViewModels.Catalog.Products.ProductCreateRequest

@{

    ViewData["Title"] = "Tạo mới sản phẩm";

    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    <script src="https://cdn.ckeditor.com/ckeditor5/27.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#txt_details'), {
                // toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
            })
            .then(editor => {
                window.editor = editor;
            })
            .catch(err => {
                console.error(err.stack);
            });
    </script>
}

<style>
    .validation-summary-valid span {
        display: none;
    }
</style>

<div class="container-fluid">
    <h1 class="mt-4">Tạo mới sản phẩm</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a style="color: #0779e4;" href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Tạo mới sản phẩm</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="Product">Về danh sách</a>
        </div>

        <div class="card-body">
            <div class="col-md-8">
                <form asp-action="Create" enctype="multipart/form-data" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CategoryId" class="control-label"></label>
                        <select asp-for="CategoryId" class="form-control form-control-md">
                            @foreach (var item in Model.Categories)
                            {
                                <option value="@item.Id">@item.Name</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label asp-for="Price" class="control-label"></label>
                        <input asp-for="Price" type="number" class="form-control" />
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Stock" class="control-label"></label>
                        <input asp-for="Stock" type="number" class="form-control" />
                        <span asp-validation-for="Stock" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <textarea id="txt_details" asp-for="Description" rows="5" class="form-control"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Details" class="control-label"></label>
                        <textarea id="txt_details_2" asp-for="Details" rows="10" class="form-control"></textarea>
                        <span asp-validation-for="Details" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ThumbnailImage" class="control-label"></label>
                        <input asp-for="ThumbnailImage" type="file" class="form-control" />
                        <span asp-validation-for="ThumbnailImage" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ProductImage" class="control-label"></label>
                        <input asp-for="ProductImage" type="file" class="form-control" />
                        <span asp-validation-for="ProductImage" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Tạo mới" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

eShopSolution.AdminApp/Views/Product/Delete.cshtml
@model eShopSolution.ViewModels.Catalog.Products.ProductDeleteRequest

@{
    ViewData["Title"] = "Xóa sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h1 class="mt-4">Xóa sản phẩm</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a style="color: #0779e4;" href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Xóa sản phẩm</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="Product">Về danh sách</a>
        </div>

        <div class="card-body">
            <div class="col-md-12">
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Id)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Id)
                    </dd>
                </dl>

                <form asp-action="Delete">
                    <input asp-for="Id" type="hidden" />
                    <input type="submit" value="Xóa" class="btn btn-danger" />
                </form>
            </div>
        </div>
    </div>
</div>

eShopSolution.AdminApp/Views/Product/Details.cshtml
@model eShopSolution.ViewModels.Catalog.Products.ProductViewModel
@inject Microsoft.Extensions.Configuration.IConfiguration Configuration
@{
    ViewData["Title"] = "Chi tiết sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h1 class="mt-4">Chi tiết sản phẩm @Model.Name</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a style="color: #0779e4;" href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Chi tiết sản phẩm</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="Product">Về danh sách</a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <td class="font-weight-bold">
                                Tên sản phẩm
                            </td>
                            <td>
                                @Html.DisplayFor(model => model.Name)
                            </td>
                        </tr>
                        <tr>
                            <td class="font-weight-bold">
                                Danh mục
                            </td>
                            <td>
                                @Html.DisplayFor(model => model.Category.Name)
                            </td>
                        </tr>
                        <tr>
                            <td class="font-weight-bold">
                                Giá tiền
                            </td>
                            <td>
                                @Model.Price.ToString("N0") <span>&#8363;</span>
                            </td>
                        </tr>
                        <tr>
                            <td class="font-weight-bold">
                                Số lượng
                            </td>
                            <td>
                                @Html.DisplayFor(model => model.Stock)
                            </td>
                        </tr>
                        <tr>
                            <td class="font-weight-bold">
                                Thông số kỹ thuật
                            </td>
                            <td>
                                @{
                                    string html = @Model.Description;
                                    string removeFirstFigure = html.Remove(0, 22);
                                    string removeLastFigure = removeFirstFigure.Remove(removeFirstFigure.Length - 9);
                                    string addedTableFormat = removeLastFigure.Insert(6, " class=\"table table-bordered table-striped\"");
                                }
                                @Html.Raw(addedTableFormat)
                            </td>
                        </tr>
                        <tr>
                            <td class="font-weight-bold">
                                Chi tiết sản phẩm
                            </td>
                            <td>
                                <style>
                                    #more {
                                        display: none;
                                    }
                                </style>
                                @Html.Raw(Model.Details)
                            </td>
                        </tr>
                        <tr>
                            <td class="font-weight-bold">
                                Ảnh đại diện
                            </td>
                            <td>
                                <img style="width:150px;height:150px" src="@(Configuration["BaseAddress"] + Model.ThumbnailImage)" alt="Alternate Text" />
                            </td>
                        </tr>
                        <tr>
                            <td class="font-weight-bold">
                                Ảnh đầy đủ
                            </td>
                            <td>
                                <img style="width:250px;height:250px" src="@(Configuration["BaseAddress"] + Model.ProductImage)" alt="Alternate Text" />
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>
<script>
    function myFunction() {
  var dots = document.getElementById("dots");
  var moreText = document.getElementById("more");
  var btnText = document.getElementById("myBtn");

  if (dots.style.display === "none") {
    dots.style.display = "inline";
    btnText.innerHTML = "Read more";
    moreText.style.display = "none";
  } else {
    dots.style.display = "none";
    btnText.innerHTML = "Read less";
    moreText.style.display = "inline";
  }
}
</script>

eShopSolution.AdminApp/Views/Product/Edit.cshtml
@model eShopSolution.ViewModels.Catalog.Products.ProductUpdateRequest

@{

    ViewData["Title"] = "Cập nhật sản phẩm";

    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    <script src="https://cdn.ckeditor.com/ckeditor5/27.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#txt_details'), {
                // toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
            })
            .then(editor => {
                window.editor = editor;
            })
            .catch(err => {
                console.error(err.stack);
            });
    </script>
}

<style>
    .validation-summary-valid span {
        display: none;
    }
</style>

<div class="container-fluid">
    <h1 class="mt-4">Cập nhật sản phẩm</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a style="color: #0779e4;" href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Cập nhật sản phẩm</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="Product">Về danh sách</a>
        </div>

        <div class="card-body">
            <div class="col-md-8">
                <form asp-action="Edit" enctype="multipart/form-data" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input asp-for="Id" type="hidden" name="Id" value="@Model.Id" />
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CategoryId" class="control-label"></label>
                        <select asp-for="CategoryId" class="form-control form-control-md">
                            @foreach (var item in Model.Categories)
                            {
                                <option value="@item.Id">@item.Name</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label asp-for="Price" class="control-label"></label>
                        <input asp-for="Price" type="number" class="form-control" />
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Stock" class="control-label"></label>
                        <input asp-for="Stock" type="number" class="form-control" />
                        <span asp-validation-for="Stock" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <textarea id="txt_details" asp-for="Description" rows="5" class="form-control"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Details" class="control-label"></label>
                        <textarea id="txt_details_2" asp-for="Details" rows="10" class="form-control"></textarea>
                        <span asp-validation-for="Details" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ThumbnailImage" class="control-label"></label>
                        <input asp-for="ThumbnailImage" type="file" class="form-control" />
                        <span asp-validation-for="ThumbnailImage" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ProductImage" class="control-label"></label>
                        <input asp-for="ProductImage" type="file" class="form-control" />
                        <span asp-validation-for="ProductImage" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Cập nhật" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

eShopSolution.AdminApp/Views/Product/Index.cshtml
@using eShopSolution.ViewModels.Common;
@model PagedResult<eShopSolution.ViewModels.Catalog.Products.ProductViewModel>
@inject Microsoft.Extensions.Configuration.IConfiguration Configuration
@{
    ViewData["Title"] = "Danh sách sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts{
    <script>
        setTimeout(function () {
            $('#msgAlert').fadeOut('slow');
        }, 2000);
    </script>
}
<div class="container-fluid">
    <h1 class="mt-4">Danh sách sản phẩm</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a style="color: #0779e4;" href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Danh sách sản phẩm</li>
    </ol>
    <div class="card mb-12">
        <div class="card-header">
            <div class="row">
                <div class="col-md-7 col-xs-12">
                    <a class="btn btn-success" asp-action="Create" asp-controller="Product">Tạo mới</a>
                </div>
                <div class="col-md-5 col-xs-12">
                    <form asp-action="Index" asp-controller="Product" method="get">
                        <div class="row">
                            <div class="col-md-4">
                                <select name="categoryId" onchange="this.form.submit()" asp-items="@ViewBag.Categories" class="form-control">
                                    <option>Chọn danh mục</option>
                                </select>
                            </div>
                            <div class="col-md-5">
                                @*name: là tên tham số*@
                                <input type="text" value="@ViewBag.Keyword" name="keyword" class="form-control" />
                            </div>
                            <div class="col-md-3">
                                <button type="submit" class="btn btn-info"><i class="fa fa-search" aria-hidden="true"></i></button>
                                <button type="button" onclick="window.location.href='/Product/Index'" class="btn btn-secondary">Đặt lại</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="card-body">
            @if (TempData["CreateProductSuccessful"] != null)
            {
                <script>
                    Swal.fire({
                        position: 'top-end',
                        icon: 'success',
                        title: 'Thêm sản phẩm thành công',
                        showConfirmButton: false,
                        timer: 1500
                    })
                </script>
            }
            else if (TempData["UpdateProductSuccessful"] != null)
            {
                <script>
                    Swal.fire({
                        position: 'top-end',
                        icon: 'success',
                        title: 'Cập nhật sản phẩm thành công',
                        showConfirmButton: false,
                        timer: 1500
                    })
                </script>
            }
            else if (TempData["DeleteProductSuccessful"] != null)
            {
                <script>
                    Swal.fire({
                        position: 'top-end',
                        icon: 'success',
                        title: 'Xóa sản phẩm thành công',
                        showConfirmButton: false,
                        timer: 1500
                    })
                </script>
            }
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th class="text-center">
                                ID
                            </th>
                            <th class="text-center">
                                Ảnh đại diện
                            </th>
                            <th>
                                Tên
                            </th>
                            <th class="text-center">
                                Giá bán
                            </th>
                            <th class="text-center">
                                Số lượng tồn
                            </th>
                            <th class="text-center">
                                Thao tác
                            </th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model.Items)
                        {
                            <tr>
                                <td class="text-center">
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td class="text-center">
                                    <img style="width:100px;height:100px" src="@(Configuration["BaseAddress"] + item.ThumbnailImage)" alt="Alternate Text" />
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td class="text-center">
                                    @item.Price.ToString("N0") <span>&#8363;</span>
                                </td>
                                <td class="text-center">
                                    @Html.DisplayFor(modelItem => item.Stock)
                                </td>
                                <td class="text-center">
                                    <button class="btn btn-primary">@Html.ActionLink("Xem chi tiết", "Details", new { id = item.Id })</button>
                                    <button class="btn btn-success">@Html.ActionLink("Cập nhật", "Edit", new { id = item.Id })</button>
                                    <button class="btn btn-danger">@Html.ActionLink("Xóa", "Delete", new { id = item.Id })</button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            @*truyền Model vào hàm InvokeAsync của class PagerViewComponent để phân trang *@
            <div>

                @await Component.InvokeAsync("Pager", Model)

            </div>
        </div>
    </div>
</div>